from __future__ import annotations

from .schemas import ToolContract


def builtin_tool_contracts() -> list[ToolContract]:
    contracts = [
        ToolContract(
            tool_id="xref.get_repository_identity",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"identity": "repository_identity"},
            requires_workspace=True,
            required_when="A client must select an isolated cache namespace before loading cached XID documents.",
        ),
        ToolContract(
            tool_id="xref.get_startup_context",
            provider="xrefkit-mcp",
            version="2",
            execution_location="server",
            side_effects="none",
            input_schema={"known_document_versions": "object?"},
            output_schema={"context": "startup_context"},
            requires_workspace=True,
            required_when="Client initialization must show base XRefKit control documents and link-resolution instructions before task routing.",
        ),
        ToolContract(
            tool_id="xref.bind_skill_run",
            provider="xrefkit-mcp",
            version="2",
            execution_location="server",
            side_effects="audit_write",
            input_schema={
                "run_id": "uuid",
                "skill_id": "string",
                "flow_id": "string?",
                "root_run_id": "uuid?",
                "parent_run_id": "uuid?",
                "work_item_id": "string?",
                "node_id": "string?",
            },
            output_schema={"binding": "skill_run_mcp_binding"},
            requires_workspace=True,
            required_when="A client created a Skill Run and must correlate subsequent MCP routing and XID access with that run.",
        ),
        ToolContract(
            tool_id="xref.end_skill_run",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="audit_write",
            input_schema={"run_id": "uuid"},
            output_schema={"binding": "ended_skill_run_mcp_binding"},
            requires_workspace=True,
            required_when="A client completed a Skill Run and must stop attributing later MCP queries to it.",
        ),
        ToolContract(
            tool_id="xref.list_knowledge_catalog",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"limit": "integer?"},
            output_schema={"entries": "knowledge_catalog_entries"},
            requires_workspace=True,
            required_when="Catalog browsing is needed without expanding knowledge body.",
            response_envelope="mcp_result_array",
        ),
        ToolContract(
            tool_id="xref.search_knowledge_catalog",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="audit_write",
            input_schema={"query": "string", "limit": "integer?"},
            output_schema={"entries": "knowledge_catalog_entries"},
            requires_workspace=True,
            required_when="A purpose or question must be matched to XID-backed knowledge.",
            response_envelope="mcp_result_array",
        ),
        ToolContract(
            tool_id="xref.expand_knowledge",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="audit_write",
            input_schema={"xid": "string"},
            output_schema={"entry": "knowledge_catalog_entry", "content": "markdown"},
            requires_workspace=True,
            required_when="The consumer explicitly needs the selected knowledge body.",
        ),
        ToolContract(
            tool_id="xref.get_knowledge_summary",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="audit_write",
            input_schema={"xid": "string"},
            output_schema={"entry": "knowledge_catalog_entry"},
            requires_workspace=True,
            required_when="The consumer needs metadata for one Knowledge entry without expanding the body.",
        ),
        ToolContract(
            tool_id="xref.get_document_by_xid",
            provider="xrefkit-mcp",
            version="2",
            execution_location="server",
            side_effects="audit_write",
            input_schema={"xid": "string", "known_version": "string?"},
            output_schema={"document": "conditional_xref_document"},
            requires_workspace=True,
            required_when="Transferred content has a links[] entry whose xid must be resolved because the client does not have local Markdown files.",
        ),
        ToolContract(
            tool_id="xref.build_knowledge_context",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="audit_write",
            input_schema={"query": "string", "limit": "integer?"},
            output_schema={"entries": "expanded_knowledge", "missing": "array"},
            requires_workspace=True,
            required_when="A bounded context pack is needed for a task.",
        ),
        ToolContract(
            tool_id="xref.list_skills",
            provider="xrefkit-mcp",
            version="4",
            execution_location="server",
            side_effects="none",
            input_schema={"limit": "integer?", "include_content": "boolean?"},
            output_schema={"entries": "skill_catalog_entries"},
            requires_workspace=True,
            required_when=(
                "Available Skills must be listed without executing them. "
                "Metadata-only by default; include_content=true returns "
                "procedure bodies and requires get_startup_context first. "
                "Tool requirements are deferred until the selected Skill is "
                "materialized through get_skill or get_skill_requirements."
            ),
            response_envelope="mcp_result_array",
        ),
        ToolContract(
            tool_id="xref.get_skill",
            provider="xrefkit-mcp",
            version="2",
            execution_location="server",
            side_effects="audit_write",
            input_schema={
                "skill_id": "string",
                "known_document_versions": "object?",
            },
            output_schema={"entry": "skill_catalog_entry"},
            requires_workspace=True,
            required_when="The client needs a Skill's meta/procedure content and skill_links that are resolved through get_document_by_xid.",
        ),
        ToolContract(
            tool_id="xref.get_skill_requirements",
            provider="xrefkit-mcp",
            version="2",
            execution_location="server",
            side_effects="none",
            input_schema={"skill_id": "string"},
            output_schema={"requirements": "skill_requirements"},
            requires_workspace=True,
            required_when="The client needs a Skill's required Knowledge, required tools, and closure contract without loading full Skill bodies.",
        ),
        ToolContract(
            tool_id="xref.rank_skills_for_purpose",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="audit_write",
            input_schema={"purpose": "string", "limit": "integer?"},
            output_schema={"results": "skill_rank_results"},
            requires_workspace=True,
            required_when="The consumer needs candidate Skills with evidence, not an automatic decision.",
            response_envelope="mcp_result_array",
        ),
        ToolContract(
            tool_id="xref.list_tool_contracts",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"contracts": "tool_contracts"},
            requires_workspace=False,
            required_when="The client performs capability handshake or audit.",
            response_envelope="mcp_result_array",
        ),
        ToolContract(
            tool_id="xref.get_client_tool_manifest",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"distribution": "client_tool_distribution"},
            requires_workspace=True,
            required_when="The client needs to know which Python tools can be installed for client-side execution.",
        ),
        ToolContract(
            tool_id="xref.get_client_tool_file",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"path": "string"},
            output_schema={"file": "client_tool_file"},
            requires_workspace=True,
            required_when="The client needs one distributed tool file content by manifest path.",
        ),
        ToolContract(
            tool_id="xref.get_client_tool_bundle",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"distribution": "client_tool_distribution", "files": "client_tool_files"},
            requires_workspace=True,
            required_when="The client needs to install all distributable Python tools for client-side execution.",
        ),
        ToolContract(
            tool_id="xref.get_client_tool_pip_package",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"package": "client_tool_pip_package"},
            requires_workspace=True,
            required_when="The client wants a pip-installable zip package for client-side XRefKit Python tools.",
        ),
        ToolContract(
            tool_id="xref.check_client_tool_versions",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={"installed": "object"},
            output_schema={"result": "client_tool_version_check"},
            requires_workspace=True,
            required_when="Client initialization must compare installed client-side tool package versions with the server manifest.",
        ),
        ToolContract(
            tool_id="xref.get_contribution_return_contract",
            provider="xrefkit-mcp",
            version="2",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"contract": "contribution_return_contract"},
            requires_workspace=True,
            required_when="A client used an MCP Skill and may return locally authored Knowledge or a deterministic tool for review.",
        ),
        ToolContract(
            tool_id="xref.submit_contribution_return",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="repo_write",
            input_schema={
                "contribution_id": "uuid",
                "kind": "knowledge|deterministic_tool",
                "title": {"type": "string", "maxLength": 256},
                "summary": {"type": "string", "maxLength": 4096},
                "files": {"type": "array", "minItems": 1, "maxItems": 64},
                "skill_content_hash": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
                "package_id": "string?",
                "knowledge_versions": {
                    "type": ["array", "null"], "maxItems": 128, "x-optional": True
                },
                "knowledge": "object?",
                "deterministic_tool": "object?",
                "proposed_target_path": "string?",
            },
            output_schema={"record": "contribution_return_manifest"},
            requires_workspace=True,
            required_when="An active Skill Run returns an inert contribution to the configured workspace review inbox.",
        ),
        ToolContract(
            tool_id="xref.list_contribution_returns",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="none",
            input_schema={},
            output_schema={"records": "contribution_return_manifests"},
            requires_workspace=True,
            required_when="A reviewer needs inbox metadata without contributed file bodies.",
            response_envelope="mcp_result_array",
        ),
        ToolContract(
            tool_id="xref.export_contribution_return",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="audit_write",
            input_schema={"contribution_id": "uuid"},
            output_schema={"bundle": "inert_contribution_review_bundle"},
            requires_workspace=True,
            required_when="A reviewer needs the complete inert contribution for governed adoption.",
        ),
        ToolContract(
            tool_id="xref.review_contribution_return",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="repo_write",
            input_schema={
                "contribution_id": "uuid",
                "decision_id": "uuid",
                "decision": "accepted|rejected",
                "reviewer": {"type": "string", "maxLength": 512},
                "decision_evidence": {"type": "string", "maxLength": 16384},
                "approval_assertion": {
                    "type": "string",
                    "maxLength": 16384,
                },
                "approved_target_path": "string?",
            },
            output_schema={"event": "immutable_contribution_review"},
            requires_workspace=True,
            required_when="A human reviewer explicitly accepts or rejects a pending contribution and fixes its canonical target evidence.",
        ),
        ToolContract(
            tool_id="xref.adopt_contribution_return",
            provider="xrefkit-mcp",
            version="1",
            execution_location="server",
            side_effects="repo_write",
            input_schema={
                "contribution_id": "uuid",
                "adoption_id": "uuid",
                "reviewer": {"type": "string", "maxLength": 512},
                "decision_evidence": {"type": "string", "maxLength": 16384},
                "approval_token": {"type": "string", "maxLength": 1024},
            },
            output_schema={"event": "immutable_contribution_adoption"},
            requires_workspace=True,
            required_when="A human-accepted contribution is promoted through the configured server-owned canonical transport.",
        ),
    ]
    for name, inputs, purpose in (
        ("get_instruction_gateway_contract", {}, "Read gateway procedure and schemas after base startup."),
        ("prepare_instruction_gateway", {"request": "object"}, "Receive an instruction before workflow execution."),
        ("route_instruction_gateway", {"assessment": "object", "policy": "object", "current_sources": "array"},
         "Select eligible models from client-reported current evidence before dispatch."),
        ("evaluate_instruction_feedback", {"feedback": "object"}, "Evaluate explicit retry and acceptance feedback."),
    ):
        contracts.append(ToolContract(
            tool_id=f"xref.{name}", provider="xrefkit-mcp", version="1",
            execution_location="server", side_effects="none", input_schema=inputs,
            output_schema={"result": "object"}, requires_workspace=False, required_when=purpose,
        ))
    for contract in contracts:
        contract.validate()
    return contracts
